import { motion } from "framer-motion";
import {
  FaArrowTrendUp,
  FaArrowUp,
  FaRupeeSign,
} from "react-icons/fa6";

const monthlyData = [
  { month: "Jan", value: 35 },
  { month: "Feb", value: 55 },
  { month: "Mar", value: 48 },
  { month: "Apr", value: 72 },
  { month: "May", value: 82 },
  { month: "Jun", value: 65 },
  { month: "Jul", value: 95 },
  { month: "Aug", value: 88 },
];

const RevenueChart = () => {
  return (
    <section className="mt-8">

      <motion.div
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        viewport={{ once: true }}
        className="rounded-3xl border border-slate-800 bg-slate-900 p-6 shadow-xl"
      >

        {/* Header */}

        <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">

          <div>

            <h2 className="flex items-center gap-3 text-3xl font-bold text-white">

              <FaArrowTrendUp className="text-blue-500" />

              Revenue Overview

            </h2>

            <p className="mt-2 text-gray-400">
              Monthly revenue generated by vehicle sales
            </p>

          </div>

          <div className="badge badge-primary badge-lg">
            2026
          </div>

        </div>

        {/* Chart */}

        <div className="mt-10 flex h-72 items-end gap-3">

          {monthlyData.map((item, index) => (

            <div
              key={item.month}
              className="flex flex-1 flex-col items-center"
            >

              <div className="flex h-60 w-full items-end">
                <motion.div
                  initial={{ scaleY: 0 }}
                  whileInView={{ scaleY: 1 }}
                  transition={{
                    delay: index * 0.1,
                    duration: 0.6,
                  }}
                  viewport={{ once: true }}
                  whileHover={{
                    scale: 1.05,
                  }}
                  style={{
                    height: `${item.value}%`,
                    transformOrigin: "bottom",
                  }}
                  className="w-full rounded-t-xl bg-gradient-to-t from-blue-700 via-cyan-500 to-cyan-300"
                />
              </div>

              <span className="mt-3 text-xs text-gray-400">
                {item.month}
              </span>

            </div>

          ))}

        </div>

        {/* Bottom Cards */}

        <div className="mt-10 grid grid-cols-1 gap-5 md:grid-cols-3">

          <div className="rounded-2xl bg-slate-800 p-5">

            <div className="flex items-center gap-3">

              <FaRupeeSign className="text-3xl text-green-400" />

              <div>

                <p className="text-gray-400">
                  Revenue
                </p>

                <h3 className="text-2xl font-bold text-white">
                  ₹24.5L
                </h3>

              </div>

            </div>

          </div>

          <div className="rounded-2xl bg-slate-800 p-5">

            <div className="flex items-center gap-3">

              <FaArrowUp className="text-3xl text-green-400" />

              <div>

                <p className="text-gray-400">
                  Growth
                </p>

                <h3 className="text-2xl font-bold text-green-400">
                  +18%
                </h3>

              </div>

            </div>

          </div>

          <div className="rounded-2xl bg-slate-800 p-5">

            <div className="flex items-center gap-3">

              <FaArrowTrendUp className="text-3xl text-cyan-400" />

              <div>

                <p className="text-gray-400">
                  Target
                </p>

                <h3 className="text-2xl font-bold text-cyan-400">
                  ₹30L
                </h3>

              </div>

            </div>

          </div>

        </div>

      </motion.div>

    </section>
  );
};

export default RevenueChart;